# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://Gamer-AI-13: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@github.com/Gamer-AI-13/soo.git"
          source_branch: "files-clone"
          destination_repo: "https://realsuperman:b731e491f7b11fb2defdc472664818fd732480a7@gitea.com/realsuperman/file.git"
          destination_branch: "master" 
          #ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          #destination_ssh_private_key: " # optional, will override `SSH_PRIVATE_KEY`